name: Run Docker Image and Host PDF

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'pdf-outputs/**'
jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull lastenigma2710/latex_compiler:latest

      - name: Run container
        run: |
          docker run --name latex-pdf-container -e WATCH_MODE=false lastenigma2710/latex_compiler:latest
          docker cp latex-pdf-container:/app/output/resume.pdf ./output.pdf
          docker rm latex-pdf-container

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: ./output.pdf

      - name: Configure Git
        run: |
          git config user.name "Rohit-2710"
          git config user.email "theenigmacode2710@gmail.com"

      - name: Commit PDF
        run: |
          mkdir -p pdf-outputs
          mv ./output.pdf ./pdf-outputs/output.pdf
          git add pdf-outputs/output.pdf
          git commit -m "Add generated PDF"
          git config --global user.name 'Rohit-2710'
          git config --global user.email 'theenigmacode27102gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}github.com/Rohit-2710/Latex_Compiler
          git commit -am "PDF Updated"
          git pushgit push

    #   - name: Push changes
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: 
    #       git push origin main
